### PR TITLE
Fix bug where certain CHO fields were not being saved to Fedora; MR-241.

### PR DESCRIPTION
**Pull request by coblej**

### CODE REVIEW

**Comment by coblej** [comment]
The spec test isn't entirely satisfactory to me.  I wanted to fill out the `contributor`, `cho_type`, and `material` fields and then test that the appropriate values appeared on the resulting `show` page but I couldn't figure out to get `Capybara` to let me fill in values for those fields since it still thinks they are hidden even with the selection of the 'Cultural Heritage Object'.

**Comment by coblej** [comment]
Well, Travis is sure not happy with my new feature test.  Let me see if I can figure that out.

**Comment by coblej** [comment]
@JocelynTriplett Travis seems to be happy with this finally.  Are you still okay with approving it?  (Getting the test to pass on Travis required changing the directory name in which the Morphosource service classes are located from `app/services/Morphosource` to `app/services/morphosource`, which is the normal Rails convention.)

**Comment by JocelynTriplett** [comment]
@coblej - Yup! :)

**Pull request merged**
