### PR TITLE
MR-133, MR-406 - Download Zipped Files from the Media Cart

### PR DESCRIPTION
**Pull request by JocelynTriplett**
- Uses media/#zip to create zip files for works represented by media cart items.
- Can download one, multiple, or all works in the media cart.
- the Previous Downloads page provides a list of works downloaded by the user.
- Works can be copied from the previously downloaded page to the media cart to be downloaded again.
- Users can delete one, multiple, or all items in their media cart.

### CODE REVIEW

**Comment by ryanfb** [comment]
If I'm reading this correctly, it looks like this changes `MediaController#zip` to take `CartItem` IDs instead of `Media` IDs—which would break [MR-394 (single `Media` download)](https://github.com/MorphoSource/MorphoSource_SF/pull/117). I think a better separation of concerns would be to keep `MediaController#zip` taking `Media` IDs, and add e.g. a `CartItemsController#download` action which takes `CartItem` IDs (or uses `item_ids = current_user.item_ids_in_cart` if none), marks them as downloaded, and finds their associated `Media` work IDs which it passes to `MediaController#zip` by using a `redirect_to` call. I'd be happy to make a first pass at writing this.

Also, the duplicated item in the zip spec is just to check we don't get errors for items with duplicate titles but different ids (eventually a fuller spec could check zip contents). I don't think we'll ever have two different items with duplicate id strings in production?

**Comment by JocelynTriplett** [comment]
@ryanfb - thanks so much for taking a look at this. Adding a download method to the CartItemsController makes sense, and I will take a crack at it. I was trying to adjust the duplicates test to account for multiple cartItems with the same work id and messed it up - I'll revert those changes. Thanks!

**Comment by JocelynTriplett** [comment]
- changes to zip and zip spec have been undone
- new download method in the cartItems controller: 
https://github.com/MorphoSource/MorphoSource_SF/blob/6922c371689b2bcf594e68c57d360b207e3a4fbb/app/controllers/morphosource/my/cart_items_controller.rb#L66-L76
- new tests in the cartItems controller spec: 
https://github.com/MorphoSource/MorphoSource_SF/blob/6922c371689b2bcf594e68c57d360b207e3a4fbb/spec/controllers/morphosource/my/cart_items_controller_spec.rb#L176-L211

**Comment by ryanfb** [comment]
Just reviewing this—the new implementation looks good, but when I run it in Vagrant and try to add a work to my cart, I get an error (at the `work_type = eval(params[:work_type])` line):

```
undefined method `model_name' for nil:NilClass
        def get_curation_concern
          work_type = eval(params[:work_type])
          @curation_concern = work_type.find(params[:work_id]) unless @curation_concern
          work_to_render = (params[:work_type].downcase.concat('/show'))
        end

app/controllers/morphosource/my/cart_items_controller.rb:160:in `eval'
app/controllers/morphosource/my/cart_items_controller.rb:160:in `eval'
app/controllers/morphosource/my/cart_items_controller.rb:160:in `get_curation_concern'

Parameters:
{"_method"=>"post",
 "locale"=>"en",
 "media_cart_id"=>"1",
 "work_id"=>"2514nk481",
 "work_type"=>"@presenter.model_name.name"}
```
(authenticity token removed)

My "add to cart" URL looks like:

    /add_to_cart?locale=en&media_cart_id=1&work_id=2514nk481&work_type=%40presenter.model_name.name

**Comment by JocelynTriplett** [comment]
Don't know how I managed to put those extra quotation marks in there - should be fixed now.

**Pull request merged**
